ManageIQ/manageiq-providers-lenovo

- manageiq-providers-lenovo.gemspec
with the name `xclarity` there has to be a `lib/xclarity.rb` to make the gem load / init.
this naming here follows the miq naming scheme
> rename gem to represent loading path

- Gemfile
- spec/controllers/cloud_network_controller_spec.rb
- spec/controllers/cloud_subnet_controller_spec.rb
- spec/controllers/ems_network_controller_spec.rb
- spec/controllers/floating_ip_controller_spec.rb
- spec/controllers/load_balancer_controller_spec.rb
- spec/controllers/network_port_controller_spec.rb
- spec/controllers/network_router_controller_spec.rb
- spec/controllers/security_group_controller_spec.rb
no need to run controller specs
for one they were running the specs for amazon and also they only should run if you have models of that kind
> remove controller specs

- manageiq-providers-lenovo.gemspec
This client gem update, adds query strings to params
This PR is needed to enable https://github.com/ManageIQ/manageiq-providers-lenovo/pull/18 to be merged.
> The one where we updated the gem

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresher.rb
Many of the current resource paths in LXCA API are being deprecated and will be discontinued soon. Thus, the way to fetch nodes through the REST API is using the `/cabinet` resource. This is how this the goal of this PR.
PS: We must wait the https://github.com/juliancheal/xclarity_client gem to support query strings through the merging of https://github.com/juliancheal/xclarity_client/pull/17, before merging this very PR.
> Fetches nodes from cabinets instead of its own resource

- spec/controllers/cloud_network_controller_spec.rb
- spec/controllers/cloud_subnet_controller_spec.rb
- spec/controllers/ems_network_controller_spec.rb
- spec/controllers/floating_ip_controller_spec.rb
- spec/controllers/load_balancer_controller_spec.rb
- spec/controllers/network_port_controller_spec.rb
- spec/controllers/network_router_controller_spec.rb
- spec/controllers/security_group_controller_spec.rb
no need to run controller specs
for one they were running the specs for amazon and also they
only should run if you have models of that kind
weird, they have been removed here https://github.com/ManageIQ/manageiq-providers-lenovo/pull/10 already. How did they re-appear?
Let's do it again
> remove controller specs again

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
The base manager class for `Lenovo::PhysicalInfraManager` was accidentally left as `InfraManager`.  This was a hold over from before the base `PhysicalInfraManager` class existed.
By updating to the correct base class, functions like `ManageIQ::Providers::PhysicalInfraManager.supported_subclasses` and `ManageIQ::Providers::PhysicalInfraManager.supported_types_and_descriptions_hash` will now return the correct list.  For example:
```
irb(main):003:0> ManageIQ::Providers::PhysicalInfraManager.supported_subclasses.map(&:name)
=> ["ManageIQ::Providers::Lenovo::PhysicalInfraManager"]
irb(main):004:0> ManageIQ::Providers::PhysicalInfraManager.supported_types_and_descriptions_hash
=> {"lenovo_ph_infra"=>"Lenovo XClarity"}
```
> Set correct base class for Lenovo Manager

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_parser.rb
This PR do the follow changes:
- Change the source name of the Lenovo's provider.
- Add the physical server identify into event hash.
This PR depends on a migration in Event Stream to add `physical_server_id`
> Change source name and add physical_server_id

- app/models/manageiq/providers/lenovo/manager_mixin.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/firmware.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Added Firmware model
Started to extract attributes to add to other tables such as:
hardwares, networks, etc.
> refactoring of refresh

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Now the refresh is parsing the follow new properties:
- `health_state`
- `power_state`
- `vendor`
> Add power_state,health_state and vendor properties in parse

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
-includes  power operations (power off, on, restart)
- location Led operations  (on, off, blinking)
@miq-bot add_label: wip, providers/physical-infrastructure
> Adds operations to the lenovo provider

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server.rb
The method "name" in physical server class is causing inconsistency when we are trying show a Physical server's name in the UI and in the REST API as well.
The method was removed to solve this issue.
> Remove method "name" from physical_server

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
Changes references to uuid to ems_ref in operations.rb.   Changes from previous PRs removing the UUID from the physical_server model where not reflected here.
@miq-bot add_label providers/physical-infrastructure
> Changes uuid references to ems_ref in operations.rb

- .travis.yml
I believe this depends on merging https://github.com/ManageIQ/manageiq/pull/13104 first since ruby_parser doesn't support 2.4.0+.
> Test updated ruby 2.3.3 and new 2.4.1.

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Adding support for parsing the location LED state, so it can be stored in the database.
> Add refresh_parser support for location LED state

- Rakefile
This is probably from the provider generator.
> Changed Amazon to Lenovo in comment.

- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_ems_inv_to_hashes.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/refresher_parse_legacy_inventory.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_blink_loc_led.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_power_off.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_power_on.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_restart.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_turn_off_loc_led.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_turn_on_loc_led.yml
ManageIQ now seems to be using webmock-2.3.2. In this new version, it appears that the authentication details (userid/password) are no longer included in the URI of the generated HTTP request. The exclusion of the authentication details, causes webmock to not use the requests stored in the cassettes because they now differ (the newly generated requests do not include the authentication details, but the requests stored cassettes do). In the prior version, webmock-1.24.6, the authentication details were included, so we did not have this problem.
> Fix unused HTTP interactions problem

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
It's no good.
Addressing:
`refresh_parser.rb:118: warning: key :computer_system is duplicated and overwritten on line 123`
> Do not define the same key twice within hash

- manageiq-providers-lenovo.gemspec
With `Dir["{app,config.lib}"]`, that only tries to find two dirs: `app`, and `config.lib` (this one isn't real, obviously).
With the fix to `Dir["{app,config.lib}"]`, it then will search through the app, config, and lib directories properly
> Fixes the definition of spec.files in gemspec

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
This PR is able to fix the vendor value, because the ManageIQ expects a downcased value  in the  [`physical_server.rb`](https://github.com/ManageIQ/manageiq/blob/master/app/models/physical_server.rb#L19) .
> Fix vendor in the physical server parse

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/event_parser_spec.rb
This PR make the fallowing changes:
- Change physical_server_ref to physical_server_id
- Change timeStamp camelcase to timestamp
- Create the function get_physical_server_id that get the id based on ref of physical server
Depends on https://github.com/ManageIQ/manageiq/pull/15133
> Change attribute name and add physical server id

- config/initializers/descendant_loader.rb
because it is automatically done from the core
> remove descendant loader initializer

- .rspec
- .rspec_ci
- README.md
- Rakefile
- bin/setup
- bin/update
- config/settings.yml
- lib/manageiq-providers-lenovo.rb
- lib/tasks/README.md
- lib/tasks/lenovo.rake
- lib/tasks_private/spec.rake
- spec/spec_helper.rb
ran the generator again with
```bash
bundle exec rails g provider <name> --path ../
```
these are the changes.
> run provider generator to sync changes from core

- app/models/manageiq/providers/lenovo/manager_mixin.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- manageiq-providers-lenovo.gemspec
- spec/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
This PR makes it possible use API Port passed in the interface form to the Client connection.
Depends on https://github.com/lenovo/xclarity_client/pull/32
> Passing the API Port to Xclarity_client

- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
This Pull Request fix the bug in the spec tests, where the API port is not passed in the second refresh parser test case.
> Pass port to refresh parser spec tests

- app/models/manageiq/providers/lenovo/manager_mixin.rb
- manageiq-providers-lenovo.gemspec
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
This Pull Request implement the discovery function for lenovo provider.
The idea is that, by receiving the ip + port, the function calls LXCA client in order to check if the params represents an appliance.
After that, it's created a new EMS instance and set all authentication with empty values. After the EMS in added, the user should update information via UI, then refreshing relationships.
Depends on: https://github.com/ManageIQ/manageiq-providers-lenovo/pull/66
> Create provider discovery feature.

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- Discover the Ip address and name server of the physical infra provider Lenovo.
After the refresh:
> Discover ip address and name server of the physical infra provider

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
This change fixes the following error which occurs during refresh:
PhysicalServer is not a subclass of ManageIQ::Providers::Lenovo::PhysicalInfraManager::PhysicalServer
Apparently, the name method was removed from PhysicalServer some time ago, but the method was still being accessed by the refresh_parser.
> Fix refresh PhysicalServer subclass error

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
Updated the device_type for ethernet ports to be 'physical_port' instead of 'ethernet port' due to pending changes in the model.
> Change device_type from 'ethernet port' to 'physical_port'

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
Adds `:dependent => :destroy` in the Physical server relationship.
Fixes https://github.com/ManageIQ/manageiq/issues/15925
> Fix physical server cascading deletion on deleting a Physical provider

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.rb
- Fix the filter of event catcher
The problem is when occurs the first refresh the method `get_last_cnn_from_events`  return `nil` and this break the filter make doing the REST API return all events.
> Fixed the filter of the  event catcher

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/runner.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream_spec.rb
- Fix the `monitor_events` problem that was being called twice at the same instant.
- Add support to `event_catcher` not be restarted after the `heartbeat_timeout` was reached.
- Refactor some things in the code.
> Fix the lenovo's event_catcher

- app/models/manageiq/providers/lenovo/manager_mixin.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
This PR is necessary to:
- Change the type of connection depends on the action. 
- Token type should be in use only for the validate button and basic for the others.
> Fix to switch connection type

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Fills in the uuid of the endpoint with a UUID that is unique to this instance of the provider. Currently this value is empty. To be more correct this field should be populated.
@agrare , @AndreyMenezes
> [WIP] Update the uid_ems to the uuid of the endpoint

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresher.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
These two methods are duplicates of what is in the refresher mixin so
they can be removed
cc @Ladas
> Cleanup duplicate refresher methods

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_parser.rb
- config/settings.yml
- spec/models/manageiq/providers/lenovo/physical_infra_manager/event_parser_spec.rb
This PR adds the custom LXCA event groups for filtering on physical server timelines. 
[Physical Server Events Filtering.pdf](https://github.com/ManageIQ/manageiq-providers-lenovo/files/1371973/Physical.Server.Events.Filtering.pdf)
> Adds LXCA event groups for event handling

- app/models/manageiq/providers/lenovo/manager_mixin.rb
This pr is able to:
Fix the provider to support the new refactor created in the `xclarity_client`.
Depends on: [PR 58 Xclarity_client ](https://github.com/lenovo/xclarity_client/pull/58)
> Add support to the fix created in the client

- app/models/manageiq/providers/lenovo/manager_mixin.rb
This PR adds port to new_ems created in discover method. This was necessary because the port was not being included in the provider model, causing an error in the UI when trying to edit any discovered provider.
> Add port to new_ems in discover method

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
This PR updates the refresh parser to support onboard network devices. In addition, guest_device related methods in the refresh parser were refactored, so future support for expansion cards will be easier to implement.
> Add support for onboard network devices

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Instead of using the product name to determine the device type, this PR updates the _get_device_type_ method to determine the device type by looking at the port type.
> Change the way device type is determined

- app/models/manageiq/providers/lenovo/manager_mixin.rb
When provider is added the credentials validation is newly done via `raw_connect` (class method) instead of `verify_credentials` (needed EMS object). Further reading on this change can be found here: ManageIQ/manageiq-ui-classic#1580
This change ensures that exceptions are handled properly, because the `verify_credentials` is not called anymore.
Related: https://github.com/ManageIQ/manageiq-ui-classic/pull/2650
Similar PRs for other providers:
- https://github.com/ManageIQ/manageiq-providers-azure/pull/161
- https://github.com/ManageIQ/manageiq-providers-hawkular/pull/100
- https://github.com/ManageIQ/manageiq-providers-scvmm/pull/41
- https://github.com/ManageIQ/manageiq-providers-google/pull/28
- https://github.com/ManageIQ/manageiq-providers-nuage/pull/40
> Fix exception handing for credential validation on raw_connect

- app/models/manageiq/providers/lenovo/physical_infra_manager/compute_node.rb
This PR remove computeNode object which was our old node object, and remove storegeNode object that was never used and will not be too.
> Remove old Lenovo provider objects

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- Support identify leds with name "identification" on refresh
https://bugzilla.redhat.com/show_bug.cgi?id=1515453
> Supporting differents identify leds name of physical servers on refresh

- app/models/manageiq/providers/lenovo/manager_mixin.rb
- Add the User-Agent when is creating the connection.
> Adding the user_agent when is creating the connection

- manageiq-providers-lenovo.gemspec
faker changed dependency of i18n which conflicts with our dependency from manageiq-consumption:
stympy/faker@9128945#diff-e79a60dc6b85309ae70a6ea8261eaf95R5
> Pinning faker gem to 1.8.3

- spec/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/runner_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
Fix failing travis tests for the new hostname validation that came after https://github.com/ManageIQ/manageiq/pull/16714
> Fixing tests for the new hostname validation

- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
To address the bug:  https://bugzilla.redhat.com/show_bug.cgi?id=1505590
Host relationships are not created to the RHEV VM instances because the service_tag field in the host table is not set. This value is set in the hardwares table associated with the host.   Joining the two tables to find the hardwares.serial_number field that matches the physical server this host is sitting on.
@miq-bot add_label wip
> searches the hardware resource for a relationship

- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
Backported https://github.com/ManageIQ/manageiq-providers-lenovo/pull/123 to Gaprindashvili, but looks like there are a few extra places that needed the same fix for Gaprindashvili. Didn't realize as that file didn't give conflict on cherry-pick...
Travis failure: https://travis-ci.org/ManageIQ/manageiq-providers-lenovo/builds/332377309
> [GAPRINDASHVILI] Additional changes for hostname validation Travis failure

- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser_dictionary_constants.rb
Depends on https://github.com/ManageIQ/manageiq/pull/16833
> AssetDetails should be AssetDetail

- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/full_refresh.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/full_refresh_second_lxca.yml
This PR adds a test case for testing a full refresh. In particular, it attempts to recreate the _guest_devices_ table problem described in Bug 1542710.
> Add spec test for a full refresh

- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
Bug Fix
======
Once the LXCA treat the memory amount in GB and the MiQ treat as MB, it needs to be converted on parse.
**Actual result**
On LXCA:
On MiQ:
**After this PR fix:**
On MiQ:
> Fixing bug in the calculate of physical server total memory

- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/component_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/config_pattern_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_server_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser_dictionary_constants.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parsers.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
__This PR is able to:__
- Create specialized classes to parse LXCA components;
- Create the `Parsers` module to namespace the new parsers structure;
- Remove components parser code from `parser.rb`, transforming it in a service class to provide the parsers methods.
__Main goals:__
- Avoid the rapid growth of the `parser.rb` due to adding of new LXCA components;
- Improve the maintainability of the Parsers structure.
> Refactoring the parse structure

- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_server_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
**Actual Result:**
When the LXCA doesn't provide this information, the disk capacity is set to 0, what could provide a wrong impression to use.
**Expected Result:**
Leave this field blank to represent the lack of information.
> Leaving the disk capacity blank if the LXCA doesn't provide this information

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_rack_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_server_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser_dictionary_constants.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parsers.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_rack.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
Parse info from a PhysicalRack
* To be merged with: ManageIQ/manageiq#16853
> Parsing physical rack

- manageiq-providers-lenovo.gemspec
'~> 0.5.x' would not pick the latest version '0.6.0', as it equals to
['>= 0.5.x', '< 0.6.0'].
Reference:
http://guides.rubygems.org/patterns/#pessimistic-version-constraint.
> Update xclarity_client gem

- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_server_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/storage_device_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
__This PR is able to:__
- Add Storage Devices to `guest_devices` physical server prop;
- Create `StorageDeviceParser` to parse the storage devices informations;
- Add some specs for new devices.
> Adding Storage Devices parser

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Bug Fix
======
When execute the refresh for the first time all Network Devices and Ports are saved successfully, but, from the second time onwards, some Network Devices are deleted and sometimes the ports are duplicated.
__Actual result:__
`guest_devices` table after first refresh:
`guest_devices` table after second refresh:
This problem occurs because the devices are distinguish by their type and uuid, and once that before this PR the uid_ems field was not filled, the network devices and its ports were distinguish incorrectly causing a wrong update.
__Bugzilla:__
https://bugzilla.redhat.com/show_bug.cgi?id=1563796
> [GAPRINDASHVILI] [BZ 1563796] Fixing the network devices and ports parser

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
This PR adds the part_number value for Physical Servers.
**Depends on:**
- [https://github.com/ManageIQ/manageiq-schema/pull/182](https://github.com/ManageIQ/manageiq-schema/pull/182) [Merged]
> Parsing partNumber for Physical Servers

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/firmware_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/network_device_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/storage_device_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
This PR is built on top of https://github.com/ManageIQ/manageiq-providers-lenovo/pull/132 and should be merged later. It moves some strings to the dictionary in several parsers and automatically removes trailing whitespaces and convert empty strings to `nil`. By doing that, the data is normalized in the database and through API access.
Depends on:
- https://github.com/ManageIQ/manageiq-providers-lenovo/pull/132
> Moving strings to dictionary and cleaning up empty and malformatted strings

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/storage_device_parser.rb
Uses the new FirmwareParser introduced at https://github.com/ManageIQ/manageiq-providers-lenovo/pull/132 to parse filters in the storage parser.
> Using firmware parser at storage parser

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/compliance_policy_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/full_refresh.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/mock_compliance_policy.yml
This PR is able to : 
* Add compliance policies information of the Physical Server in the `refresh_parser.rb` and `parser.rb`.
> Add compliance information to a server

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_rack_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_chassis.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/mock_cabinet.yml
- Parse Physical Chassis informations and maps the relationship to Physical Servers that live inside a chassi.
- Added chassis to the /cabinet mock.
Depends on:
- ~[ManageIQ/manageiq-schema#183](https://github.com/ManageIQ/manageiq-schema/pull/183) [Merged]~
> Parse Physical Chassis

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/network_device_parser.rb
This adds some vlan info to ports (guest_devices) and parse pciDevices of a Node
Did some refactor on AddinCards to use the same method to parse PciDevices as well, because they have the same fields.
Basically I am parsing the new info added to the schema on ManageIQ/manageiq-schema#165
:vlan_enabled            => port["vnicMode"], 
:vlan_key                => port["logicalPortIndex"],
Depends on: ManageIQ/manageiq-schema#165
> Parsing pci_device and vlan info to ports

- config/settings.yml
This PR is a Fix of https://github.com/ManageIQ/manageiq-providers-lenovo/pull/164 the indentation was  making the travis to fail here https://github.com/ManageIQ/manageiq/pull/17349.
I overlooked through this, my mistake
> Indentation fix on config/settings

- manageiq-providers-lenovo.gemspec
Faker gem is only used for specs. This PR moves it to development.
It is pinned as `1.8.3` due to https://github.com/ManageIQ/manageiq-providers-lenovo/pull/118.
> Move faker gem to development

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_network_ports_parser.rb
The refresh was crashing when a port didn't contain a "portInfo" field
> Fix bug when portInfo was null

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
__Current behavior__:
If the system cannot access the provider due to invalid credentials or server offline an error is throw:
```
ems_refresher_mixin.rb:50:in `refresh': undefined method `appliance' for nil:NilClass (EmsRefresh::Refreshers::EmsRefresherMixin::PartialRefreshError)
```
__Bugzilla:__
https://bugzilla.redhat.com/show_bug.cgi?id=1579934
> Fixing error while trying to refresh a provider with invalid credentials

- app/models/manageiq/providers/lenovo/manager_mixin.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
- Set the right credentials status when `AuthenticationMixin#authentication_check` is called.
__Current result__
The status is aways set to `Error`
__Expected result__
Set the status to `invalid` or `unreachable`
__Bugzilla__
https://bugzilla.redhat.com/show_bug.cgi?id=1581680
> [BZ 1581680] Fixing authentication status update

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch/operations.rb
- spec/factories/physical_switch.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/physical_switch_restart.yml
__This PR is able to:__
- Add the physical switch power operation;
- Add specs for it;
__Depends on:__
~https://github.com/lenovo/xclarity_client/pull/112~ - Merged
> Adding physical switch power operations

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/runner.rb
This pr is able to:
* Fix the event catcher break when there is no more events to be parsed.
> Fix the event catcher bug

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- Removes the updates of hostname and IP Address features.
**Reason:**
- I believe the `RefreshParser` responsibility is to handle the inventory fetching and parsing. Also, the updates are unnecessary and may create errors in some use cases.
> Remove ipaddress and hostname updates from physical_infra_manager (#1)

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/config_pattern_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_rack_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- Makes a **refactoring** on the `RefreshParser` logic and removes the use of the instance variable `@data` to return EMS inventory.
**Reason:**
- The `process_collection` method simply populates the `data` instance variable. We can return these results without the need to use variable in class scope.
**Depends on:**
- ~#173~ [merged]
> Use local variable to return inventory (#2)

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- app/models/manageiq/providers/lenovo/refresh_helper_methods.rb
- Removes the unused code inside `RefreshHelperMethods` module.
- Removes unnecessary instance variables inside `RefreshParser#initialize`.
**Depends on:**
- ~#178~ [Merged]
> Removing RefreshHelperMethods unused code (#3)

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/mock_cabinet.yml
- Parse a PhysicalStorage that is inside a PhysicalChassis
Depends on:
- ~[ManageIQ/manageiq-schema#224](https://github.com/ManageIQ/manageiq-schema/pull/224)~ [Merged]
- ~[ManageIQ/manageiq#17616](https://github.com/ManageIQ/manageiq/pull/17616)~ [Merged]
> Adding parser for PhysicalStorage inside PhysicalChassis

- app/models/manageiq/providers/lenovo/physical_infra_manager/operations/sender.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_chassis.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_chassis/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch/operations.rb
- spec/factories/physical_chassis.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/physical_chassis_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/physical_chassis_blink_loc_led.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/physical_chassis_turn_off_loc_led.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/physical_chassis_turn_on_loc_led.yml
- Move the `change_resource_state` method to a shared place to reuse in `physical_switches` and `physical_chassis` actions;
- Support Location LED actions for chassis:
- blink_loc_led;
- turn_on_loc_led;
- turn_off_loc_led;
> Adding Chassis Location Led actions

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_network_ports_parser.rb
__Current result__
For the ports that doesn't have `interfaceIndex` the following error is raise:
```
no implicit conversion of nil into String
```
__After this PR__
The `port` field is used instead the `interfaceIndex` once it will be always filled
> Fixing error while try to generate the physical switch port uuid

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- Parse the Location LED name to `physical_servers` and `physical_chassis`
__Depends on__
- ~https://github.com/ManageIQ/manageiq-schema/pull/231~ - Merged
> Parsing Location LED name

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
fixes #216 
BZ: [BugZilla](https://bugzilla.redhat.com/show_bug.cgi?id=1610524)
> Add provisioning support to Lenovo::PhysicalInfraManager

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/event_parser_spec.rb
This PR is able to parse `physical_switch_id` into events, so we can handle events for switches.
Depends on: https://github.com/ManageIQ/manageiq-schema/pull/229
> Parsing physical_swtich_id and physical_chassis_id into events

- app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/operations/sender.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_chassis/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch/operations.rb
- Refactor the routine to send `LED` and `power` operations to share between all components;
- Send the name of location LED on LED operations.
__Depends on__
~https://github.com/ManageIQ/manageiq-providers-lenovo/pull/207~ - Merged
> Adapting LED operations to parse the LED name

- config/settings.yml
Every event group in settings needs to have 3 arrays: `critical`, `detail`, `warning`.
ManageIQ/manageiq-providers-lenovo#217 introduces a couple of groups missing one or two of the required arrays, which breaks 54 ui-classic specs :): https://gist.github.com/himdel/c7b682676542936c8e4533ee58da7ebb (example https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/413927437)
Adding the missing ones here.
Cc: @matheuscmelo, @CharlleDaniel , @agrare
> config/settings - add missing fields, fixing ui-classic breakage

- .rubocop_local.yml
- app/models/manageiq/providers/lenovo/manager_mixin.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_worker.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresher.rb
- app/models/manageiq/providers/lenovo/provider.rb
- lib/tasks/lenovo.rake
- spec/spec_helper.rb
- Fix all rubocop issues;
- Removes this generated paths from rubocop lint:
- lib/manageiq-providers-lenovo.rb
- Rakefile
- manageiq-providers-lenovo.gemspec
- bin/**
**Reason:**
- Running `rubocop` on the project root will show new problems with added code.
**Depends on:**
- ~#179~ [MERGED]
> Fix all rubocop issues (#5)

- lib/manageiq/providers/lenovo/engine.rb
See ManageIQ/manageiq-ui-classic#4496 for primary motivation.
> Add plugin display name

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/network_device_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/storage_device_parser.rb
- The specialized parsers inherit from `ComponentParser`. Thus, all maps that were used in more than one parser can live inside the parent class and be used directly by Its children (without namespacing).
**Reason:**
- This enables a better cohesion on the parser classes. The maps that are common to more than one parser are available in the parent class.
> Moved common dictionary constants to component parser (#7)

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- Move the LED state information to `AssetDetail` model;
__Depends on__
~https://github.com/ManageIQ/manageiq-schema/pull/262~ - Merged
> Moving location_led_state to Asset Detail

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/management_device_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
- Extracts a `ManagementDeviceParser` from an internal part of the `PhysicalServerParser`;
**Reason:**
- Each parser should have only one responsibility.
> Extract management device parser (#10)

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
- Removes the Dictionary Constants of parsers inside `PhysicalChassisParser` and `PhysicalServerParser`;
- Adds the parsing steps to the code of the classes.
**Reason:**
- Switches and Chassis parsers had some half-parsers that were not complete parsers to be extracted. I put their logic directly on parent parsers.
> Organizing existing parsers (#11)

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/firmware_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/management_device_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_network_ports_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
- Enhances the way the parser iterates over the Dictionary of each parser. Now, the dictionary should have the simple properties as strings (as It was before) and **Symbols** to be computed properties.
**Reason:**
- `ComponentParser` was enhanced and understands a symbol inside a dictionary. The symbol used will trigger execution of a method on the parser to compute the value of a property.
> Adds support for computed properties on parser mapping (#12)

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/guest_device_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/network_device_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/storage_device_parser.rb
- Creates a Superclass `GuestDeviceParser` that is inherited by `StorageGuestDevice` and `NetworkGuestDevice`;
**Reason:**
- The two existing parsers had a lot of similar structure. However, they need a different `device_type` computation. This way, the creation of a superclass solves the problem and improves code reuse.
> Extract a GuestDeviceParser superclass from storage and network (#13)

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/runner.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_parser.rb
- config/settings.yml
- spec/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.yml
- Add pagination on Event Catcher using header `Range` from XClarity Client to fix EVM log bug
- Supress some `info` and `debug` logs, only allowing `error` ones to decrease log size on disk
- Fix connection timeout param assignment
Depends on:
- [~lenovo/xclarity_client#126 - Merged~](https://github.com/lenovo/xclarity_client/pull/126)
- [~lenovo/xclarity_client#127 - Merged~](https://github.com/lenovo/xclarity_client/pull/127)
- [~lenovo/xclarity_client#132 - Merged~](https://github.com/lenovo/xclarity_client/pull/132)
- [~ManageIQ/manageiq-providers-lenovo#228~](https://github.com/ManageIQ/manageiq-providers-lenovo/pull/228)
Related to BZ:  https://bugzilla.redhat.com/show_bug.cgi?id=1629905
> Add pagination on Event Catcher to fix EVM log bug

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/mock_cabinet.yml
- Parse PhysicalDisks data into PhysicalStorage parser
Depends on:
- [~ManageIQ/manageiq-schema#233 - Merged~](https://github.com/ManageIQ/manageiq-schema/pull/233)
- [~ManageIQ/manageiq#17700 - Merged~](https://github.com/ManageIQ/manageiq/pull/17700)
- [~lenovo/xclarity_client#131 - Merged~](https://github.com/lenovo/xclarity_client/pull/131)
- [~ManageIQ/manageiq#17972 - Merged~](https://github.com/ManageIQ/manageiq/pull/17972)
Fix related to RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1629900
> Parse PhysicalDisks into PhysicalStorage

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- Rename the `type` column name to `controller_type` on PhysicalStorageParser
Depends on:
- [~ManageIQ/manageiq-schema#276 - Merged~](https://github.com/ManageIQ/manageiq-schema/pull/276)
> Fix storage disk type to be controller_type

- app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/operations/ansible_sender.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/operations/component_ansible_sender.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_chassis/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch/operations.rb
- content/ansible_runner/requirements.yml
- spec/models/manageiq/providers/lenovo/physical_infra_manager/operations/ansible_sender_spec.rb
- Add the capability to run Ansible resources (roles and playbooks) against a LXCA or its components;
__RFC__
- How to embed https://github.com/lenovo/ansible.lenovo-lxca into `manageiq-providers-lenovo`
__Usage__
Run the following rake task to fetch roles with ansible-galaxy
```bash
bundle exec rake evm:ansible_runner:seed
```
After this, the following script is possible
```ruby
ph_manager_lenovo = ManageIQ::Providers::Lenovo::PhysicalInfraManager.first
ph_manager_lenovo.run_ansible({'role_name' => 'lenovo.lxca-inventory'})
```
> Implementing Ansible Runner engine for Lenovo's provider

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
This PR is able to get disk information from `PhysicalDisks` inside a physical storage to calculate the total disk size and store it on `total_space`.
Depends on:
- [~ManageIQ/manageiq-schema#283~](https://github.com/ManageIQ/manageiq-schema/pull/283)
> Calculate and store Physical Storage total space

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/firmware_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/guest_device_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
This pr is able to:
Fix the firmware name in the `FirmwareParse` to add support run a firmware update action by playbook.
* map the firmware name by rules
* remove the firmware parse inside canisters.
> Fix the firmware name

- app/models/manageiq/providers/lenovo/inventory/parser/component_parser/guest_device.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/guest_device_parser.rb
* Fix the issue reported in the [PR 238](https://github.com/ManageIQ/manageiq-providers-lenovo/pull/238l).
description : The `Firmware parse` of guest devices is parsing the versions of a firmware as a different firmware. The 1st refresh all the firmware are persisted, but in a 2nd refresh the firmware with the same name are [deleted](https://github.com/ManageIQ/manageiq/blob/master/app/models/ems_refresh/save_inventory.rb#L315) and only the last entry with that name remains.
> fix the firmware parse of guest device

- app/models/manageiq/providers/lenovo/inventory/parser/component_parser/physical_disk.rb
- app/models/manageiq/providers/lenovo/inventory/parser/component_parser/physical_storage.rb
- app/models/manageiq/providers/lenovo/inventory/persister/definitions/physical_infra_collections.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_disk_parser.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/physical_infra_spec_common.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/full_refresh.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/mock_storages.yml
- Parse PhysicalDisks inside a Canister
- Generate a `ems_ref` for a PhysicalDisk, since it doesn't have any field that resembles to an unique ID
Depends on:
- [ManageIQ/manageiq-schema#285](https://github.com/ManageIQ/manageiq-schema/pull/285)
- [ManageIQ/manageiq#18053](https://github.com/ManageIQ/manageiq/pull/18053)
> Parse disks into canisters

- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
Specs are created against old refresh, then values were checked against graph refresh
**depends on**: https://github.com/ManageIQ/manageiq-providers-lenovo/pull/236
> Graph refresh specs

- app/models/manageiq/providers/lenovo/physical_infra_manager/operations/ansible_sender.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server/operations.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/operations/ansible_sender_spec.rb
- Add routine to notify the user (through `NotificationMixin#notify_task_finish`) after `AnsibleRunner` execution.
__Depends on__
> Adding user notification after ansible execution

- content/ansible_runner/requirements.yml
This PR adds lxca-config to `requirements.yml` to enable server firmware update ([#18074](https://github.com/ManageIQ/manageiq/pull/18074)).
> Adding ansible-runner config requirement

- .babelrc
- .gitignore
- .gitmodules
- .npmrc
- .postcssrc.yml
- app/helpers/manageiq/providers/lenovo/toolbar_overrides/ems_physical_infra_center.rb
- app/javascript/components/apply-config-pattern-form-provider.jsx
- app/javascript/components/firmware-update-form-provider.jsx
- app/javascript/components/form/fields/config_pattern_field.js
- app/javascript/components/form/fields/firmware_check_list_field.js
- app/javascript/components/form/fields/firmware_field.js
- app/javascript/components/form/fields/physical_server_field.js
- app/javascript/components/form/lenovo_form.js
- app/javascript/components/style/firmware-update-field.css
- app/javascript/packs/component-definitions-common.js
- app/models/manageiq/providers/lenovo/inventory/parser/component_parser/config_pattern.rb
- package.json
* Add the Provision select button to make possible apply a config pattern and update the server firmware using react form. 
Depends on:
> 3° - Add provision button

- spec/factories/physical_infra_manager.rb
Other repos using this factory aren't expecting to have to set zone and other attributes since they're handled by the `:ext_management_system` base factory.  Setting the parent factory fixes this.
> Fix factory inheritence to fix issues with defaults (zone)

- app/models/manageiq/providers/lenovo/inventory/persister/definitions/physical_infra_collections.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/hardware.rb
Since all of the relationships and inventory definitions that we are using are included in the core repo, we can drop the local definitions and replace them with the definitions from the core repo.
This PR depends on:
@miq-bot assign @agrare
> Replace local inventory-related definitions

- app/helpers/manageiq/providers/lenovo/toolbar_overrides/ems_physical_infra_center.rb
After https://github.com/ManageIQ/manageiq-ui-classic/pull/5997 `to_json` is not needed and will break the data format.
Related to https://github.com/ManageIQ/manageiq-ui-classic/pull/6289 fix but **not** dependent either way.
Before:
Buttons `Firmware Update` and `Provision ` don't work on click.
After:
Buttons work as expected.
@miq-bot add_label ivanchuk/no
> Remove to_json from toolbar data as it's not needed

- app/models/manageiq/providers/lenovo/manager_mixin.rb
Saves 226 required files, around 7 MB and some time when you load the ManageIQ::Providers::Lenovo::PhysicalInfraManager.  Note, if we want to load the manager for non-operations, such as getting inventory data from the database, we shouldn't need this library.
> Autoload the constant on first use due to several places using it.

- config/settings.yml
just what it says on the tin
@miq-bot add_label cleanup
@miq-bot assign @agrare
> remove inventory object refresh from settings

- app/models/manageiq/providers/lenovo/inventory/parser/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/refresh_helper_methods.rb
The RefreshParser.ems_inv_to_hashes method was used by legacy refresh
and no longer needed
Cross repo tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/102
> Remove unused ems_inv_to_hashes method

- package.json
The dependency is not included anywhere in the codebase, so I think it's safe to get rid of that. We should also convert the forms to DDF in the future.
https://github.com/ManageIQ/manageiq-ui-classic/issues/6716#issuecomment-591974680
@miq-bot assign @himdel 
@miq-bot add_label cleanup, react
> Remove unused dependency to react-ui-components

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/runner.rb
If we don't mark the event monitor thread as running until the first
event is delivered the worker doesn't heartbeat and won't shutdown
cleanly.
> Mark the event monitor as running before first event

- config/settings.yml
Issue: Management Events from TimeLines have an empty selection
Blank selection is event `Login` and as you can see in screenshot the section with `:name:` is missing for login (for example `:name:` is present for the `:power:`)
Names are missing also for groups: Status, Network and Addition 
@miq-bot assign @agrare 
@miq-bot add_label bug
options in select box are generated by method :
```
./app/models/event_stream.rb
```
```ruby
def self.event_groups
core_event_groups = ::Settings.event_handling.event_groups.to_hash
Settings.ems.each_with_object(core_event_groups) do |(_provider_type, provider_settings), event_groups|
provider_event_groups = provider_settings.fetch_path(:event_handling, :event_groups)
next unless provider_event_groups
DeepMerge.deep_merge!( …
```
> Add event group names in setting.yml

- config/settings.yml
Missing event group names were added recently but the addition group is formally named "Creation/Addition" and was causing core spec failures
https://github.com/ManageIQ/manageiq-providers-lenovo/pull/308
https://travis-ci.com/github/ManageIQ/manageiq/jobs/367195159#L717-L746
> The addition Event group name is Creation/Addition

- app/models/manageiq/providers/lenovo/manager_mixin.rb
The default behavior for the `async-credentials` component is [changing to be optional](https://github.com/ManageIQ/manageiq-ui-classic/pull/7347), so it has to be explicitly marked as required here.
> Make the default credentials required in the provider DDF

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
Additionally, convert method definitions such as
```ruby
def supports_port?
true
end
```
to
```ruby
supports :port
```
> Convert `supports_#{op}?` to `supports?(op)`

- manageiq-providers-lenovo.gemspec
ManageIQ core brings this as a test dependency with a more-recent version (~> 3.7)
> Drop version dependency on webmock

- manageiq-providers-lenovo.gemspec
- spec/models/manageiq/providers/lenovo/manager_mixin_spec.rb
I was getting faker ruby 3.0 errors. This looked like low hanging fruit 
There is no reason to depend upon this gem just to make up an ip address
---
I also removed faker from our only dependency that requires it. so it will hopefully disapear
https://github.com/lenovo/xclarity_client/pull/155
@Fryguy are you someone who can merge / push the xclarity gem over there?
(they seemed to suggest that it could be  brought over into miq but unsure where that ended)
I ran the test locally but there are a ton of issues with that gem. it needs some love to get away from a number of abandoned gem dependencies.
> remove use of faker

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
remove supports from lenovo provider
followup to ManageIQ/manageiq#21573 and #343
> converting supported_for_create to supports :create

- app/javascript/components/apply-config-pattern-form-provider.jsx
- app/javascript/components/firmware-update-form-provider.jsx
- package.json
- yarn.lock
None of the other providers use urijs instead opting for normal template
strings. urijs is giving problems during build where it hangs on s390x
builds. In addition there have been a number of security issues with
urijs, and this is the only location that uses it.
@kavyanekkalapu @jeffibm I'm not sure how to test this...can you help me out?
cc @agrare
> Remove urijs dependency by using strings for API calls

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server/remote_console.rb
Add the :console supports feature to Lenovo Physical Servers and extract the _queue method into core.
Depends:
https://github.com/ManageIQ/manageiq/issues/22210
> Add supports :console to PhysicalServers

- lib/manageiq-providers-lenovo.rb
- lib/manageiq/providers/lenovo.rb
- spec/spec_helper.rb
Adopt convention already supported by bundler and required by zeitwerk so we don't need to tell zeitwerk to ignore this lib/gem-name.rb file.
> Drop lib/gem-name.rb in favor of lib/gem/name.rb

- app/models/manageiq/providers/lenovo/manager_mixin.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
The code which looks up the password for an existing provider had a bug where endpoint_name was not defined.  This code would work if you were adding a new provider or changing the password on an existing provider.
> Fix verify_credentials for an existing EMS

- app/models/manageiq/providers/lenovo/inventory.rb
- app/models/manageiq/providers/lenovo/inventory/collector.rb
- app/models/manageiq/providers/lenovo/inventory/parser.rb
- app/models/manageiq/providers/lenovo/inventory/parser/component_parser.rb
- app/models/manageiq/providers/lenovo/inventory/persister.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/operations/ansible_sender.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_chassis.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_chassis/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_worker.rb
Zeitwerk completely removes the need for these methods. See also: https://github.com/ManageIQ/manageiq/pull/22854
> Drop require_nested and include_concern
