ManageIQ/manageiq-providers-lenovo

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- spec/models/manageiq/providers/lenovo/refresher_spec.rb
This PR adds the ability to save inventory into the MiQ database, this links to the PR in MiQ core https://github.com/ManageIQ/manageiq/pull/11744
> Save inventory

- Gemfile
As now we've pushed it to Rubygems. This should fix the Travis/Code Climate issues. 🌮
> Removed xclairty_client being pulled from github

- .travis.yml
- README.md
Services have been enabled, so this PR adds the badges and enables Travis.
@chessbyte Please review.
> Add Services

- .rspec_ci
- .travis.yml
- tools/ci/before_install.sh
- Adding in the before_install script and rake tasks
- rspec_ci
> Make Travis Green Again

- .rubocop.yml
- .rubocop_base.yml
Having to keep all repos in sync using the rubocop_base.yml
(╯°□°）╯︵ ┻━┻
> Code Climate can't do http with rubocop inherits

- .codeclimate.yml
- .rubocop_base.yml
- .rubocop_cc.yml
> Normalize codeclimate/rubocop configuration

- config/initializers/gettext.rb
- locale/ManageIQ_Providers_Lenovo.pot
- locale/en/ManageIQ_Providers_Lenovo.po
- locale/es/ManageIQ_Providers_Lenovo.po
- locale/fr/ManageIQ_Providers_Lenovo.po
- locale/ja/ManageIQ_Providers_Lenovo.po
- locale/zh_CN/ManageIQ_Providers_Lenovo.po
- zanata.xml
* zanata.xml
* new gettext catalogs
* catalog init
> Initial setup of locale for ManageIQ::Providers::Lenovo plugin

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/runner.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/event_parser.rb
@miq-bot add_label: wip, providers/physical-infrastructure
> Adds event collection to lenovo provider

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/runner.rb
Not all devs are running ruby 2.3 yet. Removing for now.
> Removed Lonely operator.

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
@miq-bot add_label: wip, providers/physical-infrastructure
> Updates server associations and adds details

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
@miq-bot add_label: wip, providers/physical-infrastructure
> Adds collection of firmware elements from lxca

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- Save total memories
- Save total cores
> Parse provider and save(MIQ) Processor and memory infomation

- app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.rb
- Refactor the base URL used to filter events;
- Added filter parameter for not receive Events of Audit and System.
> Create events filter of Audit and System

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_retrieve_addin_cards.yml
Made changes to the refresh_parser to support the parsing of network adapter details.
> Update provider to support network adapters

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
This PR is able to : 
- Fix the `refresh_parse` to support missing values in the lxca.
> Fix the refresh parse to support missing values

- app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
- manageiq-providers-lenovo.gemspec
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_power_off_now.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_restart_mgmt_controller.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_restart_now.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_restart_to_sys_setup.yml
Update provider and spec tests to support additional power operations.
> Add provider support for additional power operations

- CHANGELOG.md
> Adding Fine-1 rollup

- app/models/manageiq/providers/lenovo/manager_mixin.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
This PR is able to: 
* Validate if the credentials is currently valid to a new provider.
Depends on: [PR 54](https://github.com/lenovo/xclarity_client/pull/54)
> Created the 'validate' to provider Lenovo

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_ems_inv_to_hashes.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_retrieve_addin_cards.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_retrieve_config_patterns.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/refresher_parse_legacy_inventory.yml
This PR updates the refresh_parser, so it can retrieve config patterns from a LXCA instance.
> Update the refresh_parser to support the retrieval of config patterns

- app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/provision_task.rb
Added the apply_config_pattern method to the physical server operations module and created a physical server provision task.
> Add support for applying a config pattern

- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_worker_spec.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_power_off.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_power_off_now.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_restart_mgmt_controller.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_restart_now.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_restart_to_sys_setup.yml
This PR is a refactor to physical infra manager tests and also adds some other tests to improve coverage.
> Physical infra manager tests refactoring and improvement

- spec/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.yml
This PR contains:
- Spec test for stream of event catcher.
> Add spec for event catcher

- CHANGELOG.md
> [GAPRINDASHVILI] [WIP][CHANGELOG] Update for Gaprindashvili-1

- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
* parse the total disk capacity from storage accessed by a physical server
> Parsing disk capacity from a physical server

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server/remote_console.rb
- spec/factories/physical_server.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/physical_server_spec.rb
Increment Lenovo physical server model to be able to fetch for remote console resource.
> Add concern for acquiring the remote console

- app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_server_parser.rb
__This PR is able to:__
- Add `NetworkDeviceParser` component;
- Parse Network Devices on PCI devices and Addin Cards.
> Parsing PCI Devices and Addin Cards as Guest Devices

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/authenticatable_provider.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_change_password_with_invalid_new_password.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_change_password_with_invalid_password.yml
- spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager_change_password_with_valid_password.yml
**This PR adds:**
* `raw_change_password` implementation defined on `physical_infra_manager.rb` on this PR: https://github.com/ManageIQ/manageiq/pull/16895
> Adding feature to change password on LXCA

- config/settings.yml
Address issue: https://github.com/ManageIQ/manageiq-providers-lenovo/issues/65.
Core PR: https://github.com/ManageIQ/manageiq/pull/17349
> cleanup lenovo's specific config from ManageIQ

- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
Camelize the power state column of a physical server list
> camelize the power state column

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresher.rb
Remove useless EmsRefresherMixin removed in https://github.com/ManageIQ/manageiq/pull/17472
> Remove useless EmsRefresherMixin

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_rack.rb
This is pluggable version of https://github.com/ManageIQ/manageiq/pull/17078/files
> Add display name for physical rack

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch.rb
This is pluggable version of https://github.com/ManageIQ/manageiq/pull/17216
> Add display name for physical switch

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_chassis.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_rack.rb
This is pluggable version of the `locale/en.yml` changes done in https://github.com/ManageIQ/manageiq/pull/17523 and https://github.com/ManageIQ/manageiq/pull/17078
> Add display names for PhysicalChassis and PhysicalRack

- app/models/manageiq/providers/lenovo/manager_mixin.rb
* Add support to raw the connection with the timeout
Dependes on : [PR Xclarity 129 ](https://github.com/lenovo/xclarity_client/pull/129)
>  Add support to raw the connection with the timeout

- app/models/manageiq/providers/lenovo/manager_mixin.rb
This pr is able to : 
* Fix connection timeout param assignment
> Fix the timeout param

- app/models/manageiq/providers/lenovo/physical_infra_manager/config_pattern.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/parser/config_pattern_parser.rb
- spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
- Add a new class for ConfigPattern
- Add `type` to ConfigPatternParser
> Add ConfigPattern class and type

- app/models/manageiq/providers/lenovo/physical_infra_manager/operations/ansible_sender.rb
- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_server/operations.rb
- Add server provision capability, using ansible.lenovo-lxca playbooks.
> Adding server provision routine based on Ansible

- .babelrc
- .gitignore
- .gitmodules
- .npmrc
- .postcssrc.yml
- package.json
This PR is able to setup the react, so we can use react to create custom button and forms
> 1º - Setup for react

- app/models/manageiq/providers/lenovo/inventory/parser/component_parser/config_pattern.rb
This pr is able to: 
* Add in the config pattern parse the type for graph refresh
> Add the config pattern type 

- .babelrc
- .gitignore
- .gitmodules
- .npmrc
- .postcssrc.yml
- app/javascript/components/form/fields/config_pattern_field.js
- app/javascript/components/form/fields/firmware_check_list_field.js
- app/javascript/components/form/fields/firmware_field.js
- app/javascript/components/form/fields/physical_server_field.js
- app/javascript/components/form/lenovo_form.js
- app/javascript/components/style/firmware-update-field.css
- package.json
This Pr is able to:
* Add react component LenovoForm
* Add react component  PhysicalServerField
* Add react component  ConfigPatternField
* Add react component FirmwareUpdateField
Depends on:
> 2º - React components

- app/models/manageiq/providers/lenovo/physical_infra_manager/physical_storage.rb
This is pluggable version of https://github.com/ManageIQ/manageiq/pull/18053/files#diff-fe5a1eb4b513afa3b7751c871a4bd3c7R871
> Add display name for Physical Storage

- lib/manageiq/providers/lenovo/engine.rb
Change plugin common methods to class methods
> Change plugin common methods to class methods

- app/javascript/components/form/fields/config_pattern_field.js
- app/javascript/components/form/fields/firmware_check_list_field.js
- app/javascript/components/form/fields/firmware_field.js
- app/javascript/components/form/fields/physical_server_field.js
@miq-bot add_label internationalization, bug
> Add missing gettext

- app/helpers/manageiq/providers/lenovo/toolbar_overrides/ems_physical_infra_center.rb
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/5937
> Toolbar update

- app/models/manageiq/providers/lenovo/manager_mixin.rb
https://github.com/ManageIQ/manageiq/issues/18818
> Add params_for_create and verify_credentials

- app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_worker.rb
Requires https://github.com/ManageIQ/manageiq/pull/19516
> Rely on the default implementation of .ems_class

- app/models/manageiq/providers/lenovo/manager_mixin.rb
Parent issue: ManageIQ/manageiq#18818
cc @h-kataria
> Adjusted DDF schema an validation for the new ProviderForm component

- app/models/manageiq/providers/lenovo/manager_mixin.rb
https://github.com/ManageIQ/manageiq-ui-classic/issues/7277
> Update DDF schema to version 2

- .codeclimate.yml
- .gitignore
- .rubocop.yml
- .rubocop_cc.yml
- .travis.yml
- README.md
- Rakefile
- bin/ci/after_script
- lib/manageiq/providers/lenovo/engine.rb
- lib/tasks/README.md
- lib/tasks_private/spec.rake
- manageiq-providers-lenovo.gemspec
- spec/spec_helper.rb
> Plugin Generator Updates

- .codeclimate.yml
- .rubocop.yml
- .rubocop_cc.yml
- manageiq-providers-lenovo.gemspec
Depends on: https://github.com/ManageIQ/miq_bot/pull/506
> Use manageiq-style

- yarn.lock
`yarn upgrade ; git commit -a`
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7563
> [KASPAROV] yarn upgrade

- lib/manageiq/providers/lenovo/engine.rb
Move logger initialization and configuration into plugins
> Move logger initialization and configuration into plugins

- .gitignore
- config/secrets.defaults.yml
- lib/manageiq/providers/lenovo/engine.rb
- spec/models/manageiq/providers/lenovo/inventory/parser/physical_infra_manager_spec.rb
- spec/spec_helper.rb
- spec/vcr_cassettes/manageiq/providers/lenovo/inventory/parser/full_refresh.yml
https://github.com/ManageIQ/manageiq/issues/21157
> Use pluggable provider secrets

- systemd/manageiq-providers-lenovo_physical_infra_manager_event_catcher@.service
- systemd/manageiq-providers-lenovo_physical_infra_manager_refresh@.service
part of https://github.com/ManageIQ/manageiq-rpm_build/pull/157
using manageiq properties and still running as root (but very close to switching over to manageiq user)
> add properties files to systemd

- systemd/manageiq-providers-lenovo_physical_infra_manager_event_catcher@.service
- systemd/manageiq-providers-lenovo_physical_infra_manager_refresh@.service
> run services as manageiq user

- app/models/manageiq/providers/lenovo/physical_infra_manager.rb
- app/models/manageiq/providers/lenovo/provider.rb
part of ManageIQ/manageiq#21573
> converting supported_for_create to supports :create

- package.json
- yarn.lock
@miq-bot assign @Fryguy
@miq-bot add_reviewer @Fryguy
@miq-bot add-label security_fix
> update urijs package

- app/models/manageiq/providers/lenovo/physical_infra_manager/provision_task.rb
Related:
* https://github.com/ManageIQ/manageiq/pull/22552
> Fix deliver_to_automate not taking args

- app/models/manageiq/providers/lenovo/manager_mixin.rb
https://github.com/ManageIQ/manageiq/issues/22845
> Add zone_id to provider validationDependencies

- lib/manageiq/providers/lenovo/engine.rb
Depends indirectly on: https://github.com/ManageIQ/manageiq/pull/23509
> Drop to_s on engine paths
